image: docker:latest

stages:
  - build

.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$GITLAB_TO_CONNECT_SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh/authorized_keys
  chmod 700 ~/.ssh
  chmod 600 ~/.ssh/authorized_keys
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

docker:image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: never
  before_script:
    - apk add openssh git curl
    - docker login registry.gitlab.com -u tkowalski@iseno.net -p "$DOCKER_TOKEN"
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  after_script:
    - docker logout registry.gitlab.com
    - echo $CI_COMMIT_TAG
