image: docker:latest

stages:
  - build

.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$GITLAB_TO_CONNECT_SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh/authorized_keys
  chmod 700 ~/.ssh
  chmod 600 ~/.ssh/authorized_keys
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

sync:
  stage: build
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
    - when: never
  before_script:
    - apk add --no-cache openssh git curl
    - *init_ssh 
  script:
    - echo "Configuring Git..."
    - git config --global user.email "tkowalski@iseno.net"
    - git config --global user.name "Tomasz Kowalski"
    
    - echo "Cloning repository from GitLab..."
    - git clone git@gitlab.com:connectors4/ai-jose-api.git repository
    - cd repository
    
    - echo "Adding GitHub remote..."
    - git remote add github git@github.com:tkowalski29/ai-jose-api-blueprint.git
    
    - echo "Fetching from GitHub..."
    - git fetch github main
    
    - echo "Checking out new branch..."
    - git checkout -b sync-github
    
    - echo "Merging GitHub main branch..."
    - git merge --no-ff github/main
    
    - echo "Pushing changes to GitLab..."
    - git push -u origin sync-github
    
    - echo "Creating merge request on GitLab..."
    - |
      curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
           --request POST "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests" \
           --form "source_branch=sync-github" \
           --form "target_branch=main" \
           --form "title=Sync with GitHub: main" \
           --form "description=Automated sync with GitHub repository"


docker:image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: never
  before_script:
    - apk add openssh git curl
    - docker login registry.gitlab.com -u tkowalski@iseno.net -p "$DOCKER_TOKEN"
    - ls -all
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  after_script:
    - docker logout registry.gitlab.com
    - echo $CI_COMMIT_TAG
